### ISSUE TITLE
Create the sculpture

### ISSUE THREAD

**Issue by OuuGiii** [OuuGiii/CG-Project-3#2]
Create a polyhedral sculpture.

The sculptural piece should consist of an icosahedron constructed using polygon meshes. 

In order to facilitate sculptural modeling, it is suggested that they generate mesh points using the icosahedron radial formula and then move each vertex so that there are no regular triangles (the icosahedron should look slightly deformed). 

The sculpture must be on a pedestal.

 3 material types:
- MeshBasicMaterial
- MeshLambertMaterial
- MeshPhongMaterial

must be defined for each object in the scene.

**Comment by OuuGiii** [comment]
Found this on the description for the project:
ENG: Note: To choose materials, we suggest using the "Material Editor" application.
POR: Nota: Para escolher materiais, sugere-se o uso da aplicação "Material Editor"

**Comment by dserafim1999** [comment]
> Found this on the description for the project:
> ENG: Note: To choose materials, we suggest using the "Material Editor" application.
> POR: Nota: Para escolher materiais, sugere-se o uso da aplicação "Material Editor"

good catch! but don't worry was only creating the base geometry today, we also have to add 3 meshes to every figure for light calculations

**Comment by OuuGiii** [comment]
I think this is the editor we should use: https://threejs.org/editor/
But I'm not sure.

**Comment by OuuGiii** [comment]
It's wierd, but it seems like the isocahedron isn't affected by light!?

**Comment by OuuGiii** [comment]
NIIICE DONE!
